### ISSUE TITLE
Add a "Common mistakes to avoid..." topic?

### ISSUE THREAD

**Issue by bobcampbell-resillion** [HbbTV-Association/Developer-Portal-Issues#1]
A recent "Improving Interoperability Survey" by HbbTVs Improving Interoperability Task Force identified that it might be helpful for the Developer Portal Guidelines to include some "Common mistakes to avoid..." as a topic. 

Unfortunately we only have some general ideas put forward for what that might include such as:

> bad application programming, e.g. application not implementing correctly state machine (stop, release...), not using transparent background for invisible apps, hardcoding SI (such as triplet) values resulting on app not launching after network changes, etc.)

Perhaps the contributors to the portal could identify more and/or expand on these and add to the portal?

(For cross reference, the original internal HbbTV Redmine issue is https://redmine.hbbtv.org/issues/12058)

**Comment by christophziegler** [comment]
Looks like there is something in place now: https://developer.hbbtv.org/tutorials/common-mistakes-to-avoid/

**Comment by david-google** [comment]
I'll close this as per comment from Christoph. It has found its way to the website already. Feel free to suggest any relevant topic we should add to this page. Many thanks
