### ISSUE TITLE
Should not use CSS3 nor >ES3 for maximum compatibility

### ISSUE THREAD

**Issue by gerardcsaperas** [HbbTV-Association/Developer-Portal-Issues#4]
After going through the tutorials there is something I haven't read and would have loved to know when I started programming for HbbTV.

There are still many TVs that do not support CSS3 (i.e. flexbox) nor modern versions of JavaScript (higher than ES3).

If you want your applications to be compatible with as much devices as possible, you should use ES3 and CSS2.

Should this be added in the tutorials somewhere?

**Comment by jpiesing** [comment]
I'm not sure where to put it in the tutorials. What about putting it in [Common Mistakes to Avoid](https://developer.hbbtv.org/tutorials/common-mistakes-to-avoid/)?

Perhaps something like this?

> Using New Web Technologies When Not Necessary
> Many HbbTV TV sets in consumer's home will be 4-5-6 years old and will probably include browsers at least 2 years older than that. In order for an app to reach the largest number of consumers, developers should be cautious in their choice of web technologies, for example avoiding CSS3 (e.g. not using features like flexbox) and not limiting themselves to ES3. Some technologies may have polyfills to bridge the gap between a modern app and an older browser.

@gerardcsaperas What do you think?

**Comment by gerardcsaperas** [comment]
I agree about including it in **Common Mistakes to Avoid**.

The text looks mostly fine, however, I think this bit might create confusion:

> [...] developers should be cautious in their choice of web technologies, for example avoiding CSS3 (e.g. not using features like flexbox) and not limiting themselves to ES3.

What do you think about:

> [...] developers should be cautious in their choice of web technologies, sticking to CSS2 (e.g. not using modern features like flexbox) and limiting themselves to ES3 is encouraged.

In any case, I think as long as it's mentioned it will be fine.

**Comment by david-google** [comment]
Before this get lost, can we agree on a text for the Common mistakes to avoid page? I do agree we should add it.

```
Using New Web Technologies When Not Necessary
Many HbbTV TV sets in consumer's home will be 4-6 years old and will probably include browsers at least 2 years older than that. In order for an app to reach the largest number of consumers, developers should be cautious in their choice of web technologies, sticking to CSS2 and and avoid CSS3 (e.g. not using features like flexbox) and limiting themselves to ES3 is encouraged. Some technologies may have polyfills to bridge the gap between a modern app and an older browser.
```

@jpiesing, @gerardcsaperas: What do you think?

**Comment by jpiesing** [comment]
How about this variation ...

> Using New Web Technologies When Not Necessary
> Many HbbTV TV sets in consumer's home will be 4-6 years old and will probably include browsers at least 2 years older than that. You can refer to [caniuse](https://www.caniuse.com) to see when a particular feature was widely implemented in desktop browsers.
> In order for an app to reach the largest number of consumers, developers should be cautious in their choice of web technologies, sticking to CSS2. Avoiding CSS3 (e.g. not using features like flexbox) and limiting themselves to ES3 is encouraged. Some technologies may have polyfills to bridge the gap between a modern app and an older browser.

**Comment by david-google** [comment]
+1

**Comment by jpiesing** [comment]
@david-google Can we close this now? It's implemented.
