### ISSUE TITLE
Common mistaks to avoid: not explicitly stopping broadcast video before playing broadband

### ISSUE THREAD

**Issue by jpiesing** [HbbTV-Association/Developer-Portal-Issues#5]
From https://redmine.hbbtv.org/issues/12215 ....

> The HbbTV specification is quite clear about what the correct behaviour is here. § A.2.1 says:
> 
> An HTML5 media element shall not be able to obtain resources that are already in use either by an A/V control object or to present broadcast video (either by the HbbTV® application through a video/broadcast object, or by the terminal when it is presenting broadcast content not under the control of a video/broadcast object). An exception to the previous requirement is when the HTML5 media element and the resources that are in use are under the control of a single MediaSynchroniser object.
> 
> Unfortunately there are no tests for this, many implementations do not follow the spec, and a number of applications expect to be able to use HTML media elements without stopping the broadcast video.

We should add something like the following as a new common mistake to avoid ..

> HbbTV applications wanting to play broadband video with the HTML5 video element need to explicitly ensure that any broadcast video that might already be in progress is stopped. Some implementations (mistakenly) stop broadcast video when not done explicitly which is the opposite of what is required. Some applications assume this mistaken behaviour and fail on correct implementations. For an application to work on as many devices as possible, any broadcast video needs to be explicitly stopped before using the HTML5 video element.

**Comment by david-google** [comment]
It is been published [here](https://developer.hbbtv.org/tutorials/common-mistakes-to-avoid/)
